inherit_from: .rubocop_todo.yml
inherit_gem:
  dlss_cops: "config/dlss_baseline.yml"

# rspec expect{...} is conventional
Style/SpaceBeforeBlockBraces:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 200
Metrics/AbcSize:
  Max: 30

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'vendor/**/*'
