require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'vendor/**/*'
    - 'tmp/**/*'

Rails:
  Enabled: true

# rspec expect{...} is conventional
Layout/SpaceBeforeBlockBraces:
  Exclude:
    - 'spec/**/*_spec.rb'

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

# Configuration parameters: AllowURI, URISchemes.
Layout/LineLength:
  Max: 200
  Exclude:
    - 'spec/features/v1/docs_controller_spec.rb'

Metrics/AbcSize:
  Max: 30

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false
