require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'vendor/**/*'
    - 'tmp/**/*'
  SuggestExtensions: false

Rails:
  Enabled: true

# rspec expect{...} is conventional
Layout/SpaceBeforeBlockBraces:
  Exclude:
    - 'spec/**/*_spec.rb'

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

# Configuration parameters: AllowURI, URISchemes.
Layout/LineLength:
  Max: 132
  AllowURI: true
  Exclude:
    - 'spec/features/v1/docs_controller_spec.rb'

Lint/BooleanSymbol:
  Enabled: false # We have a few uses of `:true` and `:false` as hash keys here.

Metrics/AbcSize:
  Max: 30

RSpec/MultipleExpectations:
  Max: 7

RSpec/MultipleMemoizedHelpers:
  Max: 6
  
RSpec/NestedGroups:
  Max: 4

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

