sudo: false
language: ruby
cache: bundler
script: bundle exec rake travis_ci 
rvm:
  - 2.1.2
  - 2.2.4
notifications:
  email:
    - pmangiafico@stanford.edu
    - laneymcg@stanford.edu
    - bess@stanford.edu
