sudo: false
language: ruby
cache: bundler
script: bundle exec rake
rvm:
  - 2.3.1 # deployed

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_script:
  - bin/rails db:test:prepare

notifications:
  email:
    - pmangiafico@stanford.edu
    - laneymcg@stanford.edu
