dist: xenial
sudo: false
language: ruby
cache: bundler
script: bundle exec rake
rvm:
  - 2.7.0

notifications:
  email:
    - pmangiafico@stanford.edu

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - CC_TEST_REPORTER_ID=cbbe86a45ca48a1b10e908c84973541df83457d6646a58930385c19e7bb85b47

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
