sudo: false
language: ruby
cache: bundler
script: bundle exec rake travis_ci 
rvm:
  - 2.3.1 # deployed
notifications:
  email:
    - pmangiafico@stanford.edu
    - laneymcg@stanford.edu
    - bess@stanford.edu
