defaults: &defaults
  filename_updating_log: "log/indexing.log"
  purl_document_path: "/purl/document_cache"
  deletes_dir: ".deletes"
  listener_path: "/purl/recent_changes"
  listener_pid_file: "<%=File.join(Rails.root,'run','listener.pid')%>"
  base_filename_finder_log: "purl_finder"
  base_path_finder_log: "<%=File.join(Rails.root,'log')%>"

development:
  <<: *defaults
  purl_document_path: "<%=Rails.root%>/spec/purl-test-fixtures/document_cache"
  listener_path: "<%=Rails.root%>/spec/purl-test-fixtures/recent_changes"
test:
  <<: *defaults
  purl_document_path: "<%=Rails.root%>/spec/purl-test-fixtures/document_cache"
  listener_path: "<%=Rails.root%>/spec/purl-test-fixtures/recent_changes"
production:
  <<: *defaults
