##
# Value (index service) that should always be provided in the `/docs/changes`
# true_targets response
ALWAYS_SEND_TRUE_TARGET:
  - SearchWorksPreview
  - ContentSearch
FILENAME_UPDATING_LOG: log/indexing.log
PURL_DOCUMENT_PATH: /purl/document_cache
DELETES_DIR: .deletes
BASE_FILENAME_FINDER_LOG: "purl_finder"
BASE_PATH_FINDER_LOG: "<%=File.join(Rails.root,'log')%>"
