##
# Value (index service) that should always be provided in the `/docs/changes`
# true_targets response
always_send_true_targets:
  - SearchWorksPreview
  - ContentSearch

# indexer_topic is one of purl_fetcher_stage or purl_fetcher_prod.
indexer_topic: testing_topic

hmac_secret: ~