##
# Value (index service) that should always be provided in the `/docs/changes`
# true_targets response
ALWAYS_SEND_TRUE_TARGET:
  - SearchWorksPreview
  - ContentSearch
PURL_DOCUMENT_PATH: /purl/document_cache
