##
# Value (index service) that should always be provided in the `/docs/changes`
# true_targets response
always_send_true_targets:
  - SearchWorksPreview
  - ContentSearch

# indexer_topic is one of purl_fetcher_stage or purl_fetcher_prod.
indexer_topic: testing_topic

hmac_secret: ~

# Mounted filesystems
filesystems:
  purl_root: "/purl/document_cache"
  stacks_root: "/stacks"
  transfer: /access-transfer-stage

features:
  legacy_purl: true

purl:
  hostname: purl.stanford.edu

image_server:
  hostname: https://imageserver
  user: admin
  password: admin
