##
# Value (index service) that should always be provided in the `/docs/changes`
# true_targets response
ALWAYS_SEND_TRUE_TARGET:
  - SearchWorksPreview
  - ContentSearch

# Can be purl_fetcher_stage or purl_fetcher_prod
indexer_topic: testing_topic
