defaults: &defaults
  collection_field: "is_member_of_collection_s"
  id_field: "id"
  collection_type: "collection"
  set_type: "set"
  fedora_type_field: "identityMetadata_objectType_t"
  druid_prefix: "druid:"
  last_changed: "published_dt"
  item_type: "item"
  fedora_prefix: "info:fedora/"
  title_field: "title_t"
  title_field_alt: "public_dc_title_t"
  catkey_field: "catkey_id_t"

development:
  <<: *defaults
test:
  <<: *defaults
staging:
  <<: *defaults
production:
  <<: *defaults
